# Generated by Django 5.0.6 on 2024-11-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraped_data',
            name='article_img',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scraped_data',
            name='body',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='scraped_data',
            name='published',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scraped_data',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
